version: '3.8'

services:
  app:
    container_name: docker-react-c
    image: docker-react-i
    build:
      context: .
    ports:
      - "3000:80"
      # map 80 in container => 3000 in local

    volumes:
      - ./src:/app




  # web:
  #   image: ten-image-cua-ban:tag-cua-ban
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - /duong-dan-toi-thu-muc-nguon:/app
  #   environment:
  #     NODE_ENV: development
  #   command: nodemon /app/server.js

  # redis:
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"
